version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:

  build:
    docker:
    - image: circleci/openjdk:stretch
    steps:
    - checkout
    - run:
        name: Run Maven to Build Project
        command: mvn clean install
