version: 2.1

steps:
      - run: mvn test install
      - run:
          command: |
            echo "Arbitrary multi-line bash"
            echo ansible-playbook -i hosts remoteplaybook.yml --limit ec2-user@18.118.2.26
